# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd3edc2c3e69ba02b85f04c120ab71ea93fef3a8b80d3c617c59609cc0651d71c4f6fd6576b35de94c6da1ee9b2bae749ba9179e47f9142dfe4cb157ded7252b

test:
  secret_key_base: c27b2adb0d9307291ed6e053d88579846a48c3254e8bf3276629a805265b98bf65fc8795fe7519bca0d50c723dc3b7164b56a918d3af04427426dffe5287d149

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
